PowerNukkit/PowerNukkit

README.md
Before, when clicked it would open the image alone in a tab.
=> Makes the GitHub Actions badge link to the build history

CHANGELOG.md, src/main/java/cn/nukkit/entity/Entity.java, src/main/java/cn/nukkit/entity/item/EntityAreaEffectCloud.java, src/main/java/cn/nukkit/entity/mob/EntityDrowned.java, src/main/java/cn/nukkit/entity/mob/EntityHusk.java, src/main/java/cn/nukkit/entity/mob/EntityPhantom.java, src/main/java/cn/nukkit/entity/mob/EntitySkeleton.java, src/main/java/cn/nukkit/entity/mob/EntityStray.java, src/main/java/cn/nukkit/entity/mob/EntityWither.java, src/main/java/cn/nukkit/entity/mob/EntityWitherSkeleton.java, src/main/java/cn/nukkit/entity/mob/EntityZombie.java, src/main/java/cn/nukkit/entity/mob/EntityZombiePigman.java, src/main/java/cn/nukkit/entity/mob/EntityZombieVillager.java, src/main/java/cn/nukkit/entity/mob/EntityZombieVillagerV1.java, src/main/java/cn/nukkit/entity/passive/EntitySkeletonHorse.java, src/main/java/cn/nukkit/entity/passive/EntityZombieHorse.java, src/main/java/cn/nukkit/potion/Potion.java
Replicate #131 and #132 to V1.X. Fixes #130
adds isUndead() and inverts potion effects when it's true
Fixes AreaEffectCloud collision rules.
Note: I had no time to test, it was pretty late here, if somebody could test I that would be great :)
=> Replicate Area Effect Cloud and Lingering potion fixes to V1.X

src/main/java/cn/nukkit/block/BlockBlueIce.java
Changes it from `2.5` to `14` as in #143
=> Fixes the blue_ice blast resistance in v1.x

src/main/java/cn/nukkit/block/BlockStrippedLog.java, src/main/java/cn/nukkit/entity/impl/BaseEntity.java, src/main/java/cn/nukkit/entity/impl/misc/EntityDroppedItem.java, src/main/java/cn/nukkit/entity/impl/misc/EntityXpOrb.java, src/main/java/cn/nukkit/item/ItemBucket.java, src/main/java/cn/nukkit/level/Explosion.java, src/main/java/cn/nukkit/level/Level.java, src/main/java/cn/nukkit/player/Player.java
This fixes:
Also consolidates #190 and pulls a fix for client movement for 1.14.30 clients
Fix #192
=> [2.0] Fix explosion behaviour with waterlogged blocks and some other bugs

src/main/java/cn/nukkit/Player.java, src/main/java/cn/nukkit/Server.java, src/main/java/cn/nukkit/entity/Entity.java, src/main/java/cn/nukkit/entity/item/EntityEndCrystal.java, src/main/java/cn/nukkit/entity/item/EntityItem.java, src/main/java/cn/nukkit/entity/item/EntityXPOrb.java, src/main/java/cn/nukkit/level/Explosion.java, src/main/java/cn/nukkit/level/Level.java
* Reduces how frequently the `SetTime` packet is sent (Related: #44)
* Fix a persistence issue with end crystals
* Improves how slow_falling prevents the entity from taking fall damage
* Fix desync about the weather between the client and the player (Related: #93)
* Move 'bug-report' into nukkit.yml
* Fix player movements with BedrockEdition `1.14.30`
* Fix drops in the water getting destroyed by explosions (Related: #193)
=> [1.X] Updates the master branch with NukkitX fixes.

CHANGELOG.md, src/main/java/cn/nukkit/Server.java, src/main/java/cn/nukkit/inventory/AnvilInventory.java
Fixes:
https://youtu.be/1j1LlaCtGpE
Also makes possible to disable the watchdog using the system parameter: `-DdisableWatchdog=true`.
Example:
```bash
java -DdisableWatchdog=true -Xmx4G -jar PowerNukkit.jar
```
Related to #222 and #225
=> [1.2.0] Fixes anvil not merging enchanted items correctly

CHANGELOG.md, src/main/java/cn/nukkit/inventory/AnvilInventory.java
The order must match the client otherwise the transaction fails.
Fix #228
=> PN-87 Fix #228 Invalid enchantment order on anvil's results

CHANGELOG.md, src/main/java/cn/nukkit/inventory/AnvilInventory.java
If the enchantment is compatible with the existing enchantments on the target:
* For Java Edition, add the final level of the enchantment on  the resulting item multiplied by the multiplier from the table below.
* For Bedrock Edition, add the difference between the final level  and the initial level on the target item multiplied by  the multiplier from the table below.
https://minecraft.gamepedia.com/Anvil/Mechanics#Costs_for_combining_enchantments
Fix #226
=> Cost calculation not applying bedrock edition reduction

CHANGELOG.md, src/main/java/cn/nukkit/level/Level.java, src/main/java/cn/nukkit/network/protocol/MoveEntityAbsolutePacket.java
Pulls NukkitX#1410 fix to 1.2.0.1-PN
(cherry picked from commit 42fac211c963cc0c07d7f2516df550788cc6027c)
=> Fix wrong flags in MoveEntityAbsolutePacket + set onGround

CHANGELOG.md, src/main/java/cn/nukkit/inventory/AnvilInventory.java, src/main/java/cn/nukkit/inventory/transaction/CraftingTransaction.java
This fixes a possible anvil exploit and fixes the items being destroyed when an anvil crafting transaction fails.
`setResult` is now deprecated because we can't force the client to accept a custom result this way, the client just ignores it. Manually changing it would make the transaction fail.
#225
=> Improves anvil security and reduces the risk of item loss

CHANGELOG.md, pom.xml, src/main/java/cn/nukkit/inventory/transaction/CraftingTransaction.java, src/main/java/cn/nukkit/item/Item.java
This essentially pulls the fix for #239 (PR #241) and moves the new method to `Item` so it can be used by the public
=> Adds equalsIgnoringEnchantmentOrder to Item and pull current 1.2.0.2-PN fixes

CHANGELOG.md, src/main/java/cn/nukkit/inventory/AnvilInventory.java, src/main/java/cn/nukkit/item/enchantment/Enchantment.java, src/main/java/cn/nukkit/item/enchantment/EnchantmentDurability.java, src/main/java/cn/nukkit/item/enchantment/EnchantmentEfficiency.java, src/main/java/cn/nukkit/item/enchantment/EnchantmentSilkTouch.java, src/main/java/cn/nukkit/item/enchantment/EnchantmentThorns.java, src/main/java/cn/nukkit/item/enchantment/bow/EnchantmentBowInfinity.java, src/main/java/cn/nukkit/item/enchantment/damage/EnchantmentDamage.java, src/main/java/cn/nukkit/item/enchantment/trident/EnchantmentTridentRiptide.java
Fixes #237 
* `Enchantment.getPowerNukkit().isItemAcceptable(Item)` to check if an enchantment can exists in a given item stack by any non-hack means.
* The secondary item rules of all enchantments listed [in the wiki](https://minecraft.gamepedia.com/Enchanting#Summary_of_enchantments)
* Review all `isCompatibleWith` implementations
=> Fixes anvil enchantment compatibility conditions

CHANGELOG.md, src/main/java/cn/nukkit/level/GlobalBlockPalette.java
Fixes the world in the screenshot of #210
It had a lot of air blocks with metadata set:
```
18:09:50 [ERROR] Found an unknown BlockId:Meta combination: 0:5, replacing with an "UPDATE!" block.
18:09:50 [ERROR] Found an unknown BlockId:Meta combination: 0:2, replacing with an "UPDATE!" block.
18:09:50 [ERROR] Found an unknown BlockId:Meta combination: 0:8, replacing with an "UPDATE!" block.
18:09:50 [ERROR] Found an unknown BlockId:Meta combination: 0:1, replacing with an "UPDATE!" block.
18:09:50 [ERROR] Found an unknown BlockId:Meta combination: 0:13, replacing with an "UPDATE!" block.
18:09:50 [ERROR] Found an unknown BlockId:Meta combination: 0:4, replacing with an "UPDATE!" block.
18:09:50 [ERROR] Found an unknown BlockId:Meta combination: 0:6, replacing with an "UPDATE!" block. …
```
=> Ignores the meta in air blocks when rendering to the client

CHANGELOG.md, src/main/java/cn/nukkit/block/BlockLeaves.java
It was spamming packets and making unnecessary world changes, was also constantly checking for logs when it could be caching the results (it was using the update_bit flag incorrectly)
Also fixes the LeavesDecayEvent being called when the leaves won't decay.
Fixes #103
=> Fixes BlockLeaves's random update logic spamming packets and LeavesDecayEvent being called when the leaves won't decay

CHANGELOG.md, src/main/java/cn/nukkit/block/BlockLiquid.java, src/main/java/cn/nukkit/block/BlockSugarcane.java, src/main/java/cn/nukkit/item/ItemBucket.java
* Fixes #79
* Makes the sugarcane breaks when the water is removed from bucket or decaying (other conditions will be handled in 1.2.1.0-PN)
* Makes huge sugarcanes breaks slowly instead of breaking all at once, just like vanilla
=> Fixes the sugarcane update logic

CHANGELOG.md, src/main/java/cn/nukkit/Player.java, src/main/java/cn/nukkit/Server.java
Fixes #238 
Messages now appears correctly:
* When the player's protocol version is not compatible with the server
* The player is kicked on login by a plugin cancelling the `PlayerLoginEvent`
* The `Player.close()` is called with any overload combination
* The server is closed
* A `DisconnectPacket` is sent to the player using the `Player.directDataPacket(DataPacket)` method
=> Fixes Disconnect messages not reaching the player sometimes

CHANGELOG.md, src/main/java/cn/nukkit/Player.java
Whatever this method is required for (something with vehicle interaction on mobile I guess) it surely doesn't have to run on every tick. Because of the usage of `getEntityPlayerLookingAt` not running this on every tick will improve the server performance especially when there are many players online. I didn't find any side effects from this change.
(cherry picked from commit 090684492c36dc8562c49c795d52997dbdcfd529)
=> Pulls> Don't run checkInteractNearby on every tick

CHANGELOG.md, src/main/java/cn/nukkit/api/DeprecationDetails.java, src/main/java/cn/nukkit/api/PowerNukkitOnly.java, src/main/java/cn/nukkit/api/Since.java, src/main/java/cn/nukkit/item/Item.java, src/main/java/cn/nukkit/item/ItemBannerPattern.java, src/main/java/cn/nukkit/item/ItemID.java
The annotations helps to flag when methods were added and when they will be removed when they are deprecated. Also helps to inform what to do with the deprecated elements. They don't depend on javadoc, so users who have only the binary files will be able to see them.
Also adds and registers the item banner. Resolves #123
=> Adds banner patterns and new annotations

CHANGELOG.md, src/main/java/cn/nukkit/api/DeprecationDetails.java, src/main/java/cn/nukkit/api/PowerNukkitOnly.java, src/main/java/cn/nukkit/api/Since.java, src/main/java/cn/nukkit/block/Block.java, src/main/java/cn/nukkit/block/BlockBeehive.java, src/main/java/cn/nukkit/level/Level.java
Fixes #113 
Adds `Block.mustSilkTouch()` and `Block.mustDrop()` to allow blocks to force the dropping behaviour when breaking.
=> Fixes behives+bees+creative and add new methods to Block

CHANGELOG.md, src/main/java/cn/nukkit/Player.java, src/main/java/cn/nukkit/api/PowerNukkitOnly.java, src/main/java/cn/nukkit/block/BlockEndPortal.java, src/main/java/cn/nukkit/entity/Entity.java
This PR:
* Fixes #272 `EntityPortalEnterEvent` not being fired when entering end portals
* Adds `Entity.inEndPortal` (protected) and `Entity.isInEndPortal()` (public)
* Fixes `BlockEndPortal` missing collision bounding box
* Fixes `Entity.checkBlockCollision()`'s over scaffolding logic outdated
=> Fixes EntityPortalEnterEvent not being fired when entering end portals

src/main/java/cn/nukkit/block/BlockPistonBase.java, src/main/java/cn/nukkit/blockentity/BlockEntityPistonArm.java, src/main/java/cn/nukkit/level/GlobalBlockPalette.java
Exception was thrown:
```
2020-07-07 17:47:21.504 [Application-Thread] ERROR - Welt "world" konnte nicht getickt werden: java.lang.IllegalArgumentException: Empty string not allowed
at cn.nukkit.nbt.tag.StringTag.<init>(StringTag.java:19)
at cn.nukkit.nbt.tag.CompoundTag.putString(CompoundTag.java:99)
at cn.nukkit.block.BlockPistonBase.doMove(BlockPistonBase.java:231)
at cn.nukkit.block.BlockPistonBase.checkState(BlockPistonBase.java:150)
at cn.nukkit.block.BlockPistonBase.onUpdate(BlockPistonBase.java:120)
at cn.nukkit.level.Level.updateAroundRedstone(Level.java:1257)
at cn.nukkit.block.BlockRedstoneWire.calculateCurrentChanges(BlockRedstoneWire.java:155)
at cn.nukkit.block.BlockRedstoneWire.updateSurroundingRedstone(BlockRedstoneWire.java:95)
at …
```
=> Fixes Piston Bugs (GlobalBlockPalette + sticky piston not pulling other sticky piston)

src/main/java/cn/nukkit/block/BlockTrapdoor.java
=> Fix crash caused by a missing pre-calculation on trapdoors

src/main/java/cn/nukkit/dispenser/FireworksDispenseBehavior.java, src/main/java/cn/nukkit/entity/data/EntityMetadata.java, src/main/java/cn/nukkit/entity/item/EntityFirework.java, src/main/java/cn/nukkit/item/ItemFirework.java
=> Fixes firework being overridden with a black creeper face

src/main/java/cn/nukkit/AdventureSettings.java
=> Fix: Spectators with OP can still break blocks (client-side)

src/main/java/cn/nukkit/level/Level.java
Block activation whilst sneaking should only be cancelled if the block has a tile like chests because blocks like logs can be activated (interacted) whilst sneaking
=> Fix for block activation whilst sneaking

src/main/java/cn/nukkit/blockstate/BigIntegerMutableBlockState.java, src/main/java/cn/nukkit/blockstate/BlockState.java, src/main/java/cn/nukkit/blockstate/BlockStateRegistry.java, src/main/java/cn/nukkit/blockstate/IBlockState.java, src/main/java/cn/nukkit/blockstate/Loggers.java, src/main/java/cn/nukkit/level/format/anvil/util/BlockStorage.java, src/test/java/cn/nukkit/level/format/anvil/util/BlockStorageTest.java
Fixes:
```java
2020-09-03 08:48:57.917 [main] FATAL - An error has occurred while trying to get the stateId of state: 533:7 - BlockProperties{bitSize=9, properties=[0-2:wall_connection_type_south, 2-4:wall_connection_type_west, 4-6:wall_connection_type_north, 6-8:wall_connection_type_east, 8-9:wall_post_bit]} - minecraft:polished_blackstone_brick_wall
cn.nukkit.blockproperty.exception.InvalidBlockPropertyMetaException: Property: wall_connection_type_south. Current Meta: 7, Invalid Meta: 3
at cn.nukkit.blockproperty.BlockProperty.getPersistenceValue(BlockProperty.java:322) ~[powernukkit.jar:?]
at cn.nukkit.blockproperty.BlockProperties.getPersistenceValue(BlockProperties.java:458) ~[powernukkit.jar:?]
at cn.nukkit.blockstate.BlockState$IntStorage.getPersistenceValue(BlockState.java:492) …
```
=> Fix error sending chunk when it has invalid block states

src/main/java/cn/nukkit/block/BlockDirt.java, src/main/java/cn/nukkit/block/BlockGrass.java, src/main/java/cn/nukkit/block/BlockIcePacked.java, src/main/java/cn/nukkit/block/BlockPodzol.java, src/main/java/cn/nukkit/blockproperty/value/DirtType.java, src/test/java/cn/nukkit/ServerTest.java, src/test/java/cn/nukkit/block/BlockGrassTest.java, src/test/java/cn/nukkit/math/NukkitRandomTest.java, src/test/java/cn/nukkit/test/answer/AnswerPositionedBlock.java, src/test/java/cn/nukkit/test/matcher/ExtraArgumentMatchers.java, src/test/java/cn/nukkit/test/matcher/InRange.java
Fix #382 
Also, when grass is decaying to dirt, it will call `BlockFadeEvent` instead of `BlockFadeEvent`
=> Fix grass spread/decay, light props of ice variants; upgrade dirt, podzol, grass, grass_path

src/main/java/cn/nukkit/Server.java, src/main/java/cn/nukkit/inventory/DoubleChestInventory.java, src/main/java/cn/nukkit/inventory/PlayerUIComponent.java, src/test/java/cn/nukkit/PlayerTest.java, src/test/java/cn/nukkit/inventory/EnchantInventoryTest.java
Affected blocks:
- Enchanting Table
- Anvil
- Grindstone
- Stonecutter
- Beacon
There were also risks involving:
- Crafting table
- 2x2 Crafting Grid
- Double chests
=> Fixes a duplication bug with 5 blocks GUI

src/main/java/cn/nukkit/Player.java, src/main/java/cn/nukkit/entity/EntityHumanType.java, src/main/java/cn/nukkit/entity/EntityLiving.java, src/main/java/cn/nukkit/item/ItemBow.java, src/main/java/cn/nukkit/level/Level.java
Fix #562 
Fix item break sounds not playing
Improves compatibility with MobPlugin and shield, the mobs will take the shield knockback now.
=> Improves combat and MobPlugin compatibility

src/main/java/cn/nukkit/Player.java, src/main/java/cn/nukkit/api/PowerNukkitDifference.java, src/main/java/cn/nukkit/block/Block.java, src/main/java/cn/nukkit/block/BlockLantern.java, src/main/java/cn/nukkit/block/BlockMoving.java, src/main/java/cn/nukkit/block/BlockUndyedShulkerBox.java, src/main/java/cn/nukkit/blockentity/BlockEntity.java, src/main/java/cn/nukkit/command/defaults/GiveCommand.java, src/main/java/cn/nukkit/entity/EntityHumanType.java, src/main/java/cn/nukkit/entity/EntityLiving.java, src/main/java/cn/nukkit/entity/projectile/EntityArrow.java, src/main/java/cn/nukkit/entity/projectile/EntityProjectile.java, src/main/java/cn/nukkit/inventory/AnvilInventory.java, src/main/java/cn/nukkit/inventory/transaction/CraftingTransaction.java, src/main/java/cn/nukkit/item/Item.java, src/main/java/cn/nukkit/level/format/generic/BaseChunk.java
=> Random fixes for 1.4.0.0-PN-SNAPSHOT

pom.xml, src/main/java/cn/nukkit/blockproperty/BlockProperty.java, src/main/java/cn/nukkit/level/Level.java, src/main/java/cn/nukkit/level/format/updater/ChunkUpdater.java, src/main/java/cn/nukkit/level/format/updater/WallUpdater.java, src/test/java/cn/nukkit/level/format/updater/WallUpdaterTest.java
```java
> 00:27:31 [WARN ] Failed to update the block X:-198, Y:86, Z:-184 at cn.nukkit.level.Level@301b89e1, could not cast it to BlockWall.
cn.nukkit.blockstate.exception.InvalidBlockStateException: The block state BlockState(blockId=139, storage=63) is invalid: Invalid block state in layer 0 at: Position(level=world,x=-198.0,y=86.0,z=-184.0)
BlockProperties{bitSize=13, properties=[0-4:wall_block_type, 4-6:wall_connection_type_south, 6-8:wall_connection_type_west, 8-10:wall_connection_type_north, 10-12:wall_connection_type_east, 12-13:wall_post_bit]}
at cn.nukkit.blockstate.IBlockState.getBlock(IBlockState.java:271) ~[server.jar:?]
at cn.nukkit.blockstate.BlockState.getBlock(BlockState.java:438) ~[server.jar:?]
at cn.nukkit.blockstate.IBlockState.getBlock(IBlockState.java:232) …
```
=> Fix: WallUpdater exception when updating walls with invalid type

src/main/java/cn/nukkit/Player.java, src/main/java/cn/nukkit/Server.java, src/main/resources/default-nukkit.yml
Add option that set players skin trusted.
If you enable this option in `nukkit.yml` (force-skin-trusted), every player skin will be trusted. (It doesn't affect when you change player's skin with plugin. It only affect login packet and player skin packet in cn.nukkit.Player.)
=> Add option that set players skin trusted

src/main/java/cn/nukkit/Player.java
The client defaults to `clear` when no weather is sent, an optimization was done long ago but forgot
to remove the previous unoptimized call leading to it sending two packages at times, and always sending at least one.
=> Fixes reduntant sendWeather call being sent to client.

src/main/java/cn/nukkit/entity/item/EntityBoat.java, src/main/java/cn/nukkit/item/ItemBoat.java
Fix Boat problems.
Changed:
- Boat use Variant instead of woodID.
- Save Variant.
- New method: getVariant(), setVariant(int variant)
- Drop boat item properly when it killed.
- Boat doesn't make Smoke particles.
- Use Variant tag when spawning. (ItemBoat)
- Reduce ItemBoat count in Adventure mode.
=> Fix Boat problems

src/main/java/cn/nukkit/block/BlockGrass.java, src/main/java/cn/nukkit/block/BlockGrassPath.java
Fix the path block won't decay to dirt when you place a solid block above it (Fix #904)
Dirt Path:
- Fix the path block won't decay to dirt when you place a solid block above it
- Fix hardness and resistance
Grass Block:
- Fix resistance
=> Fix the path block won't decay to dirt when you place a solid block above it (Fix #904)

src/main/java/cn/nukkit/entity/Entity.java
=> Reduce the log level of a message when an entity could not be loaded

src/main/java/cn/nukkit/level/format/anvil/util/BlockStorage.java, src/main/java/cn/nukkit/level/format/generic/BaseChunk.java, src/test/java/cn/nukkit/level/format/generic/BaseChunkTest.java
Some generators were setting blocks outside the chunk range, Nukkit truncate the bits in that situation, PowerNukkit were throwing exceptions.
Fix #1138
=> Fixes backward compatibility with generators.

src/main/java/cn/nukkit/item/enchantment/damage/EnchantmentDamageAll.java
This pull request changes the formula to the correct one.
For the calculation formula, I referred to the following site.
https://minecraft.fandom.com/wiki/Sharpness#Usage
=> Wrong calculation of additional damage for sharpness enchantments

src/main/java/cn/nukkit/block/BlockConcrete.java, src/main/java/cn/nukkit/block/BlockConcretePowder.java
The names for Concrete and Concrete Powder when getting a block, is just concrete, it doesn't specify the colored name of the blocks, this is just a simple fix for it!
=> Fixed the names for BlockConcrete and BlockConcretePowder

pom.xml
This pull request bumps log4j to 2.15.0, fixes maven workflow failure present in #1263 #1264
=> Bump log4j to 2.15.0

src/main/java/cn/nukkit/potion/Potion.java
The speed potion should last 90 seconds, not 480. After my changes, the duration of the action corresponds to the original one.
https://www.youtube.com/watch?v=QFIFExQ3XVo
=> Fix speed potion duration

CHANGELOG.md, pom.xml, src/main/java/cn/nukkit/level/util/PalettedBlockStorage.java
Fixes:
```java
2022-04-20 18:01:22.032 [main] INFO  - Enabling AntiXray v1.2.3-PN.1
2022-04-20 18:01:22.041 [main] FATAL - An error occurred while enabling the plugin AntiXray, 1.2.3-PN.1, cn.wode490390.nukkit.antixray.AntiXray
java.lang.NoSuchMethodError: cn.nukkit.level.util.PalettedBlockStorage.<init>(Lcn/nukkit/level/util/BitArrayVersion;)V
at cn.wode490390.nukkit.antixray.WorldHandler.<clinit>(WorldHandler.java:69) ~[?:?]
at cn.wode490390.nukkit.antixray.AntiXray.onEnable(AntiXray.java:162) ~[?:?]
at cn.nukkit.plugin.PluginBase.setEnabled(PluginBase.java:105) ~[custom.jar:?]
at cn.nukkit.plugin.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:120) ~[custom.jar:?]
at cn.nukkit.plugin.PluginManager.enablePlugin(PluginManager.java:461) [custom.jar:?]
at …
```
=> Backward compatibility fix with AntiXRay PowerNukkit port.
