PowerNukkit/PowerNukkit

- src/main/java/cn/nukkit/entity/EntityLiving.java
Source: https://github.com/NukkitX/Nukkit/pull/1010
> noDamageTicks should make the entity completely invulnerable while active

- src/main/java/cn/nukkit/Player.java
Source: https://github.com/NukkitX/Nukkit/pull/962
> Kick banned player with set reason

- src/main/java/cn/nukkit/Player.java
- src/main/java/cn/nukkit/entity/item/EntityVehicle.java
- src/main/java/cn/nukkit/event/vehicle/VehicleDamageByEntityEvent.java
- src/main/java/cn/nukkit/event/vehicle/VehicleDamageEvent.java
- src/main/java/cn/nukkit/event/vehicle/VehicleDestroyByEntityEvent.java
- src/main/java/cn/nukkit/event/vehicle/VehicleDestroyEvent.java
Source: https://github.com/NukkitX/Nukkit/pull/879
> Vehicle event fix

- src/main/java/cn/nukkit/entity/Entity.java
Source: https://github.com/NukkitX/Nukkit/pull/845
> Entity: avoid bad hack on high load which causes bugs on entity move

- src/main/java/cn/nukkit/Server.java
- src/main/java/cn/nukkit/event/server/ServerStopEvent.java
Source: https://github.com/NukkitX/Nukkit/pull/834
> Add basic ServerStopEvent

- src/main/java/cn/nukkit/block/BlockBone.java
- src/main/java/cn/nukkit/block/BlockEndPortalFrame.java
- src/main/java/cn/nukkit/block/BlockJukebox.java
- src/main/java/cn/nukkit/block/BlockObserver.java
Source: https://github.com/NukkitX/Nukkit/pull/811
> Fix block placement

- src/main/java/cn/nukkit/entity/item/EntityMinecartChest.java
- src/main/java/cn/nukkit/entity/item/EntityMinecartHopper.java
- src/main/java/cn/nukkit/inventory/ContainerInventory.java
- src/main/java/cn/nukkit/inventory/InventoryType.java
- src/main/java/cn/nukkit/inventory/MinecartChestInventory.java
- src/main/java/cn/nukkit/inventory/MinecartHopperInventory.java
Source: https://github.com/NukkitX/Nukkit/pull/837
> Implement minecart inventory

- src/main/java/cn/nukkit/Player.java
- src/main/java/cn/nukkit/entity/EntityHuman.java
- src/main/java/cn/nukkit/entity/EntityHumanType.java
- src/main/java/cn/nukkit/inventory/InventoryType.java
- src/main/java/cn/nukkit/inventory/PlayerOffhandInventory.java
- src/main/java/cn/nukkit/item/ItemBow.java
Source: https://github.com/NukkitX/Nukkit/pull/940
> Implement offhand

- .github/ISSUE_TEMPLATE.md
- .github/workflows/maven.yml
- CHANGELOG.md
- Dockerfile
- Jenkinsfile
- README.md
- pom.xml
Changes the project name to PowerNukkit, adds a README, removes the test badge and changes the build status badge to one generated by GitHub actions (will only show a status after this branch is merged, theoretically)
> Updates the project files based on the master branch

- .github/workflows/maven.yml
- README.md
Short version of #136 but to v1.X, only needed to update the badges and the GitHub Action name
> Removes the tests badges and changes the build status to GitHub Actions

- src/main/java/cn/nukkit/block/BlockBarrier.java
- src/main/java/cn/nukkit/block/BlockBlueIce.java
- src/main/java/cn/nukkit/block/BlockSmoothStone.java
- src/main/java/cn/nukkit/entity/Entity.java
- src/main/java/cn/nukkit/entity/impl/hostile/EntityDrowned.java
- src/main/java/cn/nukkit/entity/impl/hostile/EntityHusk.java
- src/main/java/cn/nukkit/entity/impl/hostile/EntityPhantom.java
- src/main/java/cn/nukkit/entity/impl/hostile/EntitySkeleton.java
- src/main/java/cn/nukkit/entity/impl/hostile/EntityStray.java
- src/main/java/cn/nukkit/entity/impl/hostile/EntityWither.java
- src/main/java/cn/nukkit/entity/impl/hostile/EntityWitherSkeleton.java
- src/main/java/cn/nukkit/entity/impl/hostile/EntityZombie.java
- src/main/java/cn/nukkit/entity/impl/hostile/EntityZombiePigman.java
- src/main/java/cn/nukkit/entity/impl/hostile/EntityZombieVillager.java
- src/main/java/cn/nukkit/entity/impl/misc/EntityAreaEffectCloud.java
- src/main/java/cn/nukkit/entity/impl/passive/EntitySkeletonHorse.java
- src/main/java/cn/nukkit/entity/impl/passive/EntityZombieHorse.java
- src/main/java/cn/nukkit/level/provider/leveldb/serializer/BlockEntitySerializer.java
- src/main/java/cn/nukkit/potion/Potion.java
- src/main/java/cn/nukkit/registry/BlockRegistry.java
> Pull the commits from NukkitX:2.0 into v2.0/block/ice-block/fixing-on-break

- src/main/java/cn/nukkit/block/BlockTrapdoor.java
Replicates the #158 fix to 1.X
> [1.X] Fixes trapdoor behaviour on redstone signal

- src/main/java/cn/nukkit/block/Block.java
- src/main/java/cn/nukkit/block/BlockCampfire.java
- src/main/java/cn/nukkit/block/BlockDriedKelp.java
- src/main/java/cn/nukkit/block/BlockLiquid.java
- src/main/java/cn/nukkit/block/BlockTrapdoor.java
- src/main/java/cn/nukkit/block/BlockTrapdoorIron.java
- src/main/java/cn/nukkit/block/BlockWater.java
- src/main/java/cn/nukkit/blockentity/BlockEntityCampfire.java
- src/main/java/cn/nukkit/item/ItemBucket.java
- src/main/java/cn/nukkit/level/BlockPosition.java
- src/main/java/cn/nukkit/level/Level.java
- src/main/java/cn/nukkit/level/chunk/ChunkSection.java
- src/main/java/cn/nukkit/level/chunk/UnsafeChunk.java
- src/main/java/cn/nukkit/registry/BlockRegistry.java
Related to #164 #162 #154 #165 #166 #158 #163 #168
> [2.X] Updates the 2.0-migration branch with NukkitX 2.0 fixes.

- src/main/java/cn/nukkit/IPlayer.java
- src/main/java/cn/nukkit/Player.java
- src/main/java/cn/nukkit/entity/Entity.java
- src/main/java/cn/nukkit/entity/EntityLiving.java
- src/main/java/cn/nukkit/inventory/PlayerInventory.java
- src/main/java/cn/nukkit/level/Level.java
Fixes #148
Related #44
Same as #171, but using an in house branch.
> [1.X] Updates the master branch with NukkitX fixes.

- src/main/java/cn/nukkit/level/LevelData.java
- src/main/java/cn/nukkit/nbt/tag/StringTag.java
* Fixes exception on startup without custom generator options
Makes generatorOptions never null.
* Null string is not an empty string, changes a exception message.
Reference: NukkitX#1174
> [2.0] Fix a startup error

- src/main/java/cn/nukkit/block/BlockLava.java
- src/main/java/cn/nukkit/block/BlockLavaStill.java
- src/main/java/cn/nukkit/block/BlockLiquid.java
- src/main/java/cn/nukkit/block/BlockWater.java
- src/main/java/cn/nukkit/block/BlockWaterStill.java
- src/main/java/cn/nukkit/registry/BlockRegistry.java
> Fix crash when waterlogged flowing water meets still water

- CHANGELOG.md
- pom.xml
- src/main/java/cn/nukkit/Player.java
- src/main/java/cn/nukkit/block/BlockSugarcane.java
- src/main/java/cn/nukkit/event/player/PlayerJumpEvent.java
This merge pulls the following additions from NukkitX's 1.X branch:
* NukkitX#1403
* NukkitX#1405
> Adds PlayerJumpEvent and makes sugar canes call BlockGrowEvent

- CHANGELOG.md
- src/main/java/cn/nukkit/Player.java
> The level is charged twice when operating an anvil

- CHANGELOG.md
- src/main/java/cn/nukkit/Player.java
- src/main/java/cn/nukkit/inventory/AnvilInventory.java
- src/main/java/cn/nukkit/inventory/transaction/CraftingTransaction.java
- src/main/java/cn/nukkit/level/Level.java
- src/main/java/cn/nukkit/network/protocol/MoveEntityAbsolutePacket.java
Please check the [1.2.0.1-PN release](https://github.com/GameModsBR/PowerNukkit/releases/tag/v1.2.0.1-PN) for details.
> Pushes 1.2.0.1-PN changes to 1.2.1.0-PN-SNAPSHOT

- CHANGELOG.md
- src/main/java/cn/nukkit/inventory/transaction/CraftingTransaction.java
> Anvil fails to merge some enchantments because the ordering mismatches

- CHANGELOG.md
- src/main/java/cn/nukkit/item/enchantment/EnchantmentThorns.java
- src/main/java/cn/nukkit/item/enchantment/bow/EnchantmentBowKnockback.java
Fixes #240 
The anvil were charging fewer levels to merge thorn books and more levels to merge punch books.
> Thorns and punch weights were incorrect

- CHANGELOG.md
- src/main/java/cn/nukkit/inventory/AnvilInventory.java
- src/main/java/cn/nukkit/item/enchantment/EnchantmentDurability.java
- src/main/java/cn/nukkit/item/enchantment/bow/EnchantmentBowInfinity.java
- src/main/java/cn/nukkit/item/enchantment/trident/EnchantmentTridentRiptide.java
This pull some fixes from #244 for quicker release
> Fixes some checks in anvil and some wrong enchantment compatibility rules

- CHANGELOG.md
- src/main/java/cn/nukkit/level/GlobalBlockPalette.java
This will help to find what is causing "UPDATE!" block to appears.
> Makes the server log when it finds an unknown BlockId:Meta combination

- CHANGELOG.md
- src/main/java/cn/nukkit/command/defaults/TeleportCommand.java
> Fixes the command: /tp player 0 1 2

- CHANGELOG.md
- src/main/java/cn/nukkit/block/BlockWood.java
- src/main/java/cn/nukkit/block/BlockWood2.java
> Fix Stripping old full bark log results in a wrong block

- CHANGELOG.md
- src/main/java/cn/nukkit/block/BlockIcePacked.java
> Wrong Packed and Blue Ice break time with hands

- CHANGELOG.md
- src/main/java/cn/nukkit/level/Explosion.java
> Fixes wrong explosion behaviour with waterlogged block

- CHANGELOG.md
- src/main/java/cn/nukkit/command/defaults/DebugPasteCommand.java
- src/main/java/cn/nukkit/utils/Watchdog.java
`/status` information were printed to the console but was not collected and wasn't affecting anything, now it's also reported.
I also changed the new issue links to point to PowerNukkit.
> Fix /status information in /debugpaste not being collected

- CHANGELOG.md
70e56398deb0e9e921f13cfae1ab4dc70ea76067 should be included in this PR but I accidentally pushed straight to master
> Move CapturingCommandSender to its own public class

- CHANGELOG.md
- src/main/java/cn/nukkit/block/BlockLeaves.java
> Fixes leaves log scanning logic

- CHANGELOG.md
- src/main/java/cn/nukkit/block/BlockLeaves.java
- src/main/java/cn/nukkit/utils/Hash.java
Also pulls #258 to 1.2.1.0-PN-SNAPSHOT
> Adds Hash.hashBlock(Vector3)

- CHANGELOG.md
- src/main/java/cn/nukkit/entity/item/EntityEndCrystal.java
- src/main/java/cn/nukkit/level/Explosion.java
- src/main/java/cn/nukkit/network/protocol/LoginPacket.java
This PR pulls NukkitX#1425, NukkitX#1431 and NukkitX#1439 to 1.2.0.2-PN
> Fixes issues with end crystals, block's inventory drops by explosions and LoginPacket's protocol check

- CHANGELOG.md
- src/main/java/cn/nukkit/Player.java
- src/main/java/cn/nukkit/entity/item/EntityEndCrystal.java
- src/main/java/cn/nukkit/level/Explosion.java
- src/main/java/cn/nukkit/network/protocol/LoginPacket.java
Also syncs with NukkitX's master and PowerNukkit's snapshot/1.2.0.x branches.
> Adds getter for checkMovement and a the reason to kick messages

- CHANGELOG.md
- src/main/java/cn/nukkit/entity/item/EntityFishingHook.java
> Fixes fishing hooks not attaching to entities.

- CHANGELOG.md
- src/main/java/cn/nukkit/Player.java
- src/main/java/cn/nukkit/command/defaults/XpCommand.java
Fixes #95
`/xp` command now makes sound each 5 levels
> Enhances the level up sound and makes /xp make sound too

- CHANGELOG.md
- src/main/java/cn/nukkit/entity/item/EntityFishingHook.java
> Removes fishing hook without player

- src/main/java/cn/nukkit/entity/item/EntityFishingHook.java
> Fixes fishing hooks using mount instead of DATA_TARGET_EID

- CHANGELOG.md
- src/main/java/cn/nukkit/Player.java
- src/main/java/cn/nukkit/inventory/AnvilInventory.java
- src/main/java/cn/nukkit/inventory/BeaconInventory.java
- src/main/java/cn/nukkit/inventory/EnchantInventory.java
- src/main/java/cn/nukkit/inventory/FakeBlockUIComponent.java
- src/main/java/cn/nukkit/inventory/GrindstoneInventory.java
- src/main/java/cn/nukkit/inventory/StonecutterInventory.java
> Fix item losses when player gets disconnected with items in open fake inventories

- CHANGELOG.md
- src/main/java/cn/nukkit/api/DeprecationDetails.java
- src/main/java/cn/nukkit/api/PowerNukkitOnly.java
- src/main/java/cn/nukkit/api/Since.java
- src/main/java/cn/nukkit/block/Block.java
- src/main/java/cn/nukkit/level/Level.java
Also makes the new annotation automatically inherited
> Adds Block.afterRemoval(), called when the block is replaced

- CHANGELOG.md
- src/main/java/cn/nukkit/block/BlockLiquid.java
- src/main/java/cn/nukkit/block/BlockWater.java
- src/main/java/cn/nukkit/item/ItemBucket.java
It will update the sugarcane immediately now
> Fixes what happens when you replace the sugarcane's water with an other block

- CHANGELOG.md
- src/main/java/cn/nukkit/block/BlockButton.java
- src/main/java/cn/nukkit/block/BlockLever.java
> Fixes levers and buttons don't replace the snow layers

- CHANGELOG.md
- pom.xml
Check the [CHANGELOG](https://github.com/GameModsBR/PowerNukkit/blob/master/CHANGELOG.md#1210-pn---2020-06-07-check-the-milestone) for details.
> Release PowerNukkit 1.2.1.0-PN

- src/main/java/cn/nukkit/Player.java
- src/main/java/cn/nukkit/inventory/PlayerInventory.java
> Prevent spamming open inv key from crashing client

- src/main/java/cn/nukkit/Player.java
- src/main/java/cn/nukkit/network/Network.java
- src/main/java/cn/nukkit/network/protocol/EmotePacket.java
This PR pulls NukkitX#1515 to PowerNukkit. It's a followup to #306 and #307
> Add support for Emotes

- src/main/java/cn/nukkit/Player.java
It will fix multiple output crafting like cake (by Extollite)
> Fix multiple output crafting.

- CHANGELOG.md
- src/main/java/cn/nukkit/Player.java
- src/main/java/cn/nukkit/network/RakNetInterface.java
> Fixes incompatibility with the regular version of GAC

- src/main/java/cn/nukkit/Server.java
- src/main/java/cn/nukkit/block/Block.java
- src/main/java/cn/nukkit/entity/mob/EntityHoglin.java
- src/main/java/cn/nukkit/entity/mob/EntityPiglin.java
- src/main/java/cn/nukkit/entity/mob/EntityZoglin.java
- src/main/java/cn/nukkit/entity/passive/EntityStrider.java
- src/main/java/cn/nukkit/network/protocol/AddEntityPacket.java
Sloved (#290)
From (NukkitX#1522)
> Add new Entitys

- src/main/java/cn/nukkit/blockstate/BlockStateRegistry.java
> Fix regression of a compatibility issue with FAWE (air blocks with meta)

- src/main/java/cn/nukkit/resourcepacks/ResourcePackManager.java
- src/main/java/cn/nukkit/resourcepacks/ZippedResourcePack.java
Fix #368 allow resource packs to have sub-folder inside itself
> Allow resource packs to have sub-folder inside itself

- src/main/java/cn/nukkit/inventory/PlayerUIInventory.java
- src/main/java/cn/nukkit/inventory/transaction/InventoryTransaction.java
- src/main/java/cn/nukkit/item/Item.java
This fixes #379 , an issue while registering fuzzy crafting recipes
Fixes some issues with inventory clicks
> Fixes crafting recipes and pulls changes from upstream

- src/main/java/cn/nukkit/block/Block.java
- src/main/java/cn/nukkit/block/BlockBasalt.java
- src/main/java/cn/nukkit/block/BlockID.java
- src/main/java/cn/nukkit/block/BlockLava.java
- src/main/java/cn/nukkit/block/BlockPolishedBasalt.java
Also implements the basalt generator
> Implements Basalt and Polished Basalt

- src/main/java/cn/nukkit/block/BlockTorch.java
> Fixes torch placement issues

- README.md
> Correct the word (README.md)

- .dockerignore
- Dockerfile
- hooks/post_checkout
https://hub.docker.com/r/powernukkit/powernukkit
> Adjusting the docker cloud builds

- .dockerignore
- .github/pull.yml
- .github/workflows/maven.yml
- Dockerfile
- pom.xml
- src/main/java/cn/nukkit/block/BlockBrewingStand.java
- src/main/java/cn/nukkit/blockentity/BlockEntity.java
- src/main/java/cn/nukkit/blockentity/BlockEntityBrewingStand.java
- src/main/java/cn/nukkit/blockentity/BlockEntityFurnace.java
- src/main/java/cn/nukkit/inventory/CraftingManager.java
> Fixes brewing stand issues

- src/main/java/cn/nukkit/Player.java
- src/main/java/cn/nukkit/level/Level.java
> Fix: Reconnecting while in the nether shows orverworld sky

- src/main/java/cn/nukkit/block/BlockMelon.java
> Fix melon not breaking when pushed by piston

- src/main/java/cn/nukkit/item/ItemBucket.java
> Fix: players can use buckets in adventure mode

- src/main/java/cn/nukkit/block/Block.java
- src/main/java/cn/nukkit/block/BlockID.java
- src/main/java/cn/nukkit/block/BlockSnowLayer.java
- src/main/java/cn/nukkit/block/BlockStructureVoid.java
- src/main/java/cn/nukkit/blockproperty/value/StructureVoidType.java
- src/main/resources/block_ids.csv
Adds block property, fix error on startup and interaction with lever and snow_layer
> Fixes structure void implementation and merges with bleeding

- src/main/java/cn/nukkit/Player.java
- src/main/java/cn/nukkit/Server.java
- src/main/java/cn/nukkit/block/Block.java
- src/main/java/cn/nukkit/block/BlockID.java
- src/main/java/cn/nukkit/block/BlockLodestone.java
- src/main/java/cn/nukkit/blockentity/BlockEntity.java
- src/main/java/cn/nukkit/blockentity/BlockEntityLodestone.java
- src/main/java/cn/nukkit/command/defaults/SetBlockCommand.java
- src/main/java/cn/nukkit/entity/EntityHumanType.java
- src/main/java/cn/nukkit/inventory/BaseInventory.java
- src/main/java/cn/nukkit/inventory/PlayerInventory.java
- src/main/java/cn/nukkit/item/Item.java
- src/main/java/cn/nukkit/item/ItemCompassLodestone.java
- src/main/java/cn/nukkit/item/ItemID.java
- src/main/java/cn/nukkit/level/Position.java
- src/main/java/cn/nukkit/level/generator/populator/impl/PopulatorGroundCover.java
- src/main/java/cn/nukkit/level/generator/populator/impl/PopulatorOre.java
- src/main/java/cn/nukkit/math/Vector3.java
- src/main/java/cn/nukkit/network/Network.java
- src/main/java/cn/nukkit/network/protocol/ItemStackRequestPacket.java
- src/main/java/cn/nukkit/network/protocol/ItemStackResponsePacket.java
- src/main/java/cn/nukkit/network/protocol/PositionTrackingDBClientRequestPacket.java
- src/main/java/cn/nukkit/network/protocol/PositionTrackingDBServerBroadcastPacket.java
- src/main/java/cn/nukkit/positiontracking/NamedPosition.java
- src/main/java/cn/nukkit/positiontracking/PositionTracking.java
- src/main/java/cn/nukkit/positiontracking/PositionTrackingService.java
- src/main/java/cn/nukkit/positiontracking/PositionTrackingStorage.java
- src/test/java/cn/nukkit/positiontracking/PositionTrackingStorageTest.java
Adds 2 more packets that were deleted by mistake:
> Adds lodestone, lodestone_compass and related packets

- src/main/java/cn/nukkit/Player.java
- src/main/java/cn/nukkit/block/Block.java
- src/main/java/cn/nukkit/block/BlockCauldron.java
- src/main/java/cn/nukkit/block/BlockHoney.java
- src/main/java/cn/nukkit/block/BlockIce.java
- src/main/java/cn/nukkit/block/BlockLiquid.java
- src/main/java/cn/nukkit/block/BlockSlime.java
- src/main/java/cn/nukkit/blockstate/BlockStateRegistry.java
- src/main/java/cn/nukkit/level/Level.java
- src/main/java/cn/nukkit/network/protocol/ProtocolInfo.java
- src/main/java/cn/nukkit/plugin/PluginBase.java
- src/main/java/cn/nukkit/utils/Utils.java
> A few enhancements for plugin developers

- src/main/java/cn/nukkit/inventory/transaction/InventoryTransaction.java
- src/test/java/cn/nukkit/PlayerTest.java
- src/test/java/cn/nukkit/ServerTest.java
> Fix a duplication exploit

- src/main/java/cn/nukkit/Player.java
- src/main/java/cn/nukkit/Server.java
- src/main/resources/default-nukkit.yml
> Implements setting to disable safe spawning

- .gitattributes
- src/main/java/cn/nukkit/block/BlockBed.java
- src/main/java/cn/nukkit/block/BlockFlowerPot.java
- src/main/java/cn/nukkit/block/BlockFungus.java
- src/main/java/cn/nukkit/block/BlockGrassPath.java
- src/main/java/cn/nukkit/block/BlockLantern.java
- src/main/java/cn/nukkit/block/BlockRedstoneWire.java
- src/main/java/cn/nukkit/blockstate/BlockState.java
- src/main/java/cn/nukkit/inventory/CraftingManager.java
- src/main/java/cn/nukkit/item/Item.java
- src/test/java/cn/nukkit/blockstate/IBlockStateTest.java
```java
[ERROR] Could not tick level "world": java.lang.UnsupportedOperationException: Negative BigIntegers are not supported (nearly infinite bits)
at cn.nukkit.math.NukkitMath.bitLength(NukkitMath.java:122)
at cn.nukkit.blockstate.IMutableBlockState.repairStorage(IMutableBlockState.java:217)
at cn.nukkit.blockstate.IMutableBlockState.setDataStorage(IMutableBlockState.java:103)
at cn.nukkit.block.Block.setDataStorage(Block.java:1904)
at cn.nukkit.blockstate.IBlockState.getBlock(IBlockState.java:269)
at cn.nukkit.blockstate.BlockState.getBlock(BlockState.java:453)
at cn.nukkit.blockstate.IBlockState.getBlockRepairing(IBlockState.java:374)
at cn.nukkit.level.Level.getBlock(Level.java:1634)
at cn.nukkit.level.Level.getBlock(Level.java:1606)
at cn.nukkit.level.Level.getBlock(Level.java:1590) …
```
> Random fixes for 1.4.0.0-PN-SNAPSHOT

- src/main/java/cn/nukkit/Player.java
- src/main/java/cn/nukkit/block/BlockGrindstone.java
- src/main/java/cn/nukkit/inventory/GrindstoneInventory.java
- src/main/java/cn/nukkit/inventory/transaction/CraftingTransaction.java
- src/main/java/cn/nukkit/inventory/transaction/InventoryTransaction.java
- src/main/java/cn/nukkit/network/protocol/CraftingEventPacket.java
> Fix: Cancelling CraftItemEvent makes you loose the recipe

- src/main/java/cn/nukkit/Server.java
- src/main/java/cn/nukkit/block/Block.java
- src/main/java/cn/nukkit/level/ChunkManager.java
- src/main/java/cn/nukkit/level/Level.java
- src/main/java/cn/nukkit/level/format/ChunkSection.java
- src/main/java/cn/nukkit/level/format/anvil/ChunkSection.java
- src/main/java/cn/nukkit/level/format/generic/BaseChunk.java
- src/main/java/cn/nukkit/level/format/generic/BaseFullChunk.java
- src/main/java/cn/nukkit/level/format/generic/EmptyChunkSection.java
- src/main/java/cn/nukkit/math/BlockVector3.java
- src/main/java/cn/nukkit/math/ChunkVector2.java
- src/main/java/cn/nukkit/math/Vector3.java
Additionally fixes #638 , unloaded levels trying to tick
> Create method to execute fast block scanning on big areas

- src/main/java/cn/nukkit/block/Block.java
- src/main/java/cn/nukkit/block/BlockNetherPortal.java
- src/main/java/cn/nukkit/block/BlockObsidian.java
- src/main/java/cn/nukkit/entity/Entity.java
- src/main/java/cn/nukkit/level/EnumLevel.java
- src/main/java/cn/nukkit/level/Level.java
- src/main/java/cn/nukkit/level/format/generic/BaseChunk.java
- src/main/java/cn/nukkit/level/format/generic/BaseFullChunk.java
- src/main/java/cn/nukkit/math/Vector2.java
- src/main/java/cn/nukkit/math/Vector3.java
The portals now take you to the correct coordinate in the other dimension;
The server now looks for portals already generated in the surroundings of the destination to take the player there instead of always generating a new portal.
Fix #289 
Fix #36
> Fixes some nether portal issues

- src/main/java/cn/nukkit/Player.java
- src/main/java/cn/nukkit/block/BlockLever.java
- src/main/java/cn/nukkit/block/BlockObserver.java
- src/main/java/cn/nukkit/block/BlockRedstoneWire.java
- src/main/java/cn/nukkit/block/BlockSkull.java
- src/main/java/cn/nukkit/blockentity/BlockEntitySkull.java
Fix #640 projectiles not decrementing in adventure game mode
Fix #642 Observer Clock is not working
Enderdragon head's mouth now moves when activated with redstone power
> Random fixes

- src/main/java/cn/nukkit/level/Level.java
> Fix infinite recursive loop when repairing a block

- src/main/java/cn/nukkit/entity/mob/EntityZoglin.java
> Zoglin is undead

- src/main/java/cn/nukkit/Player.java
- src/main/java/cn/nukkit/inventory/transaction/InventoryTransaction.java
This pull request adds curse enchantments, Curse of Binding and Cursed of Vanishing
> Added curse enchantments

- src/main/java/cn/nukkit/block/Block.java
- src/main/java/cn/nukkit/entity/Entity.java
- src/main/java/cn/nukkit/entity/item/EntityItem.java
Fixes issues #671 and #672 and all item blocks having lava resistance
Closes #671.
Closes #672.
> Fixes all blocks having lava resistance and non-netherite items not burning

- src/main/java/cn/nukkit/blockentity/BlockEntityHopper.java
> Fix: Property facing_direction not found while ticking entity hopper

- src/main/java/cn/nukkit/entity/Entity.java
Usage : collideWithBlock(Block.class)
> Adds generic method to check if an entity collides with any given block type.

- src/main/java/cn/nukkit/Player.java
- src/main/java/cn/nukkit/block/Block.java
- src/main/java/cn/nukkit/block/BlockSoulSand.java
- src/main/java/cn/nukkit/block/BlockSoulSoil.java
- src/main/java/cn/nukkit/item/enchantment/Enchantment.java
- src/main/java/cn/nukkit/item/enchantment/EnchantmentSoulSpeed.java
This pr adds the Soul Speed Enchantment
> Adds the Soul Speed Enchantment

- src/main/java/cn/nukkit/Player.java
- src/main/java/cn/nukkit/Server.java
- src/main/resources/default-nukkit.yml
Add new option that enable or disable checkMovement.
It will be useful for the server that want to disable checkMovement without enabling allow flight.
> Add new option that enable or disable checkMovement

- src/main/java/cn/nukkit/Player.java
Implement TimeSinceRest
New Method:
- Player.getTimeSinceRest() : It will return TimeSinceRest (int)
- Player.setTimeSinceRest(int) : It will set TimeSinceRest
It will be useful to get how long the player hasn't slept. (tick) Also, it will be useful for Phantom natural spawning.
> Add TimeSinceRest to Player

- src/main/java/cn/nukkit/block/BlockWaterLily.java
> lily pads now can be placed above water

- .idea/codeStyles/Project.xml
- src/main/java/cn/nukkit/api/Unsigned.java
- src/main/java/cn/nukkit/block/Block.java
- src/main/java/cn/nukkit/block/BlockDoor.java
- src/main/java/cn/nukkit/block/BlockTrapdoor.java
- src/main/java/cn/nukkit/blockstate/BigIntegerMutableBlockState.java
- src/main/java/cn/nukkit/blockstate/BlockState.java
- src/main/java/cn/nukkit/blockstate/ByteMutableBlockState.java
- src/main/java/cn/nukkit/blockstate/IBlockState.java
- src/main/java/cn/nukkit/blockstate/IMutableBlockState.java
- src/main/java/cn/nukkit/blockstate/IntMutableBlockState.java
- src/main/java/cn/nukkit/blockstate/LongMutableBlockState.java
- src/main/java/cn/nukkit/blockstate/MutableBlockState.java
- src/main/java/cn/nukkit/blockstate/ZeroMutableBlockState.java
- src/main/java/cn/nukkit/level/format/anvil/ChunkSection.java
- src/main/java/cn/nukkit/level/format/anvil/LayerStorage.java
- src/main/java/cn/nukkit/level/format/anvil/util/BlockStorage.java
- src/main/java/cn/nukkit/utils/Validation.java
- src/test/java/cn/nukkit/level/format/anvil/ChunkSectionTest.java
```java
03:51:32 [ERROR] Error while unloading a chunk: cn.nukkit.utils.ChunkException: Error saving chunk (-200, -55)
03:51:32 [ERROR] Throwing
cn.nukkit.utils.ChunkException: Error saving chunk (-200, -55)
at cn.nukkit.level.format.anvil.Anvil.saveChunk(Anvil.java:243) ~[server.jar:?]
at cn.nukkit.level.Level.unloadChunk(Level.java:3332) [server.jar:?]
at cn.nukkit.level.Level.unloadChunk(Level.java:3293) [server.jar:?]
at cn.nukkit.level.Level.unloadChunks(Level.java:3667) [server.jar:?]
at cn.nukkit.level.Level.doGarbageCollection(Level.java:3565) [server.jar:?]
at cn.nukkit.Server.tickProcessor(Server.java:1154) [server.jar:?]
at cn.nukkit.Server.start(Server.java:1101) [server.jar:?]
at cn.nukkit.Server.<init>(Server.java:757) [server.jar:?]
at cn.nukkit.Nukkit.main(Nukkit.java:120) …
```
> Fix: ChunkSection.allocateBlob() IndexOutOfBoundsException: Index: 3, Size: 3

- src/main/java/cn/nukkit/level/Level.java
- src/test/java/cn/nukkit/block/BlockEnderChestTest.java
> Fix: Blocks disappearing when building up

- src/main/java/cn/nukkit/potion/Potion.java
Add a missing potion type (SLOWNESS_IV)
> Add a missing potion type (SLOWNESS_IV)

- CHANGELOG.md
- src/main/java/cn/nukkit/entity/Entity.java
https://discordapp.com/channels/728280425255927879/728280425255927882/779799513162055701
> Fix: Mobs going into the ground with MobPlugin

- CHANGELOG.md
- src/main/java/cn/nukkit/level/Level.java
> Fix #770 bamboo and items of blocks with id > 255 not dropping

- CHANGELOG.md
- src/main/java/cn/nukkit/level/format/anvil/RegionLoader.java
> Fix #766 Error saving region files with content over 2 GB

- CHANGELOG.md
- src/main/java/cn/nukkit/block/BlockScaffolding.java
> Fix #777 Falling block falling though scaffolds

- CHANGELOG.md
- src/main/java/cn/nukkit/inventory/GrindstoneInventory.java
> Fix #776 Grindstone cant remove enchants

- CHANGELOG.md
- src/main/java/cn/nukkit/level/format/anvil/Anvil.java
- src/main/java/cn/nukkit/level/format/generic/BaseLevelProvider.java
- src/main/java/cn/nukkit/utils/LevelException.java
- src/main/java/cn/nukkit/utils/Utils.java
Also sets PowerNukkit as the server brand in the level.dat file
Fix #765
> Improves level.dat saving to prevent world corruption

- src/main/java/cn/nukkit/Player.java
Remove @PowerNukkitOnly from TimeSinceRest
It was added in Nukkit too. (https://github.com/CloudburstMC/Nukkit/commit/ebc4ff489582f53d01f4cb6656dd1744f6465d13)
> Remove @PowerNukkitOnly from TimeSinceRest

- src/main/java/cn/nukkit/entity/Entity.java
Totem give Fire Resistance I not II
> Totem give Fire Resistance I not II

- src/main/java/cn/nukkit/block/BlockLantern.java
Fix and update lanterns
- Fix hardness
- Fix resistance
- Can be waterlogged
> Fix and update lanterns

- src/main/java/cn/nukkit/block/BlockBeeNest.java
Updae Bee Nest block color 
- Bee Nest block color is yellow
> Update Bee Nest block color

- src/main/java/cn/nukkit/block/BlockMushroom.java
Mushrooms can be placed and grown both types of Nylium.
> Mushrooms can be placed and grown both types of Nylium

- src/main/java/cn/nukkit/entity/passive/EntityStrider.java
Fix Strider max health. (15 -> 20)
> Fix Strider max health

- src/main/java/cn/nukkit/block/BlockComposter.java
Fix and update composter
- Fix resistance
- Shroomlight can be used in a composter
- Fix hardness
> Fix and update composter

- src/main/java/cn/nukkit/network/protocol/ProtocolInfo.java
It will allow players to join, but if you have any resource packs it will crash the client.
> Protocol bump

- src/main/java/cn/nukkit/block/BlockDirt.java
- src/main/java/cn/nukkit/block/BlockGrass.java
- src/main/java/cn/nukkit/block/BlockGrassPath.java
- src/main/java/cn/nukkit/block/BlockMycelium.java
- src/main/java/cn/nukkit/block/BlockPodzol.java
Update Grass Path (Dirt Path)
- Grass Path has been renamed to Dirt Path
- Dirt Path can now be made on top of dirt, coarse dirt, mycelium, and podzol
> Update Grass Path (Dirt Path)

- src/main/java/cn/nukkit/block/BlockSweetBerryBush.java
Fix Sweet Berry Bush drops (Fix duplication problem)
> Fix Sweet Berry Bush drops (Fix duplication problem)

- src/main/java/cn/nukkit/block/BlockNetherPortal.java
- src/main/java/cn/nukkit/dispenser/BucketDispenseBehavior.java
> Fix nether portal replace by right-clicking with lava or water bucket and dispensers now can destroy nether portals

- src/main/java/cn/nukkit/entity/Entity.java
> Fix for missing effect particles after re-login

- src/main/java/cn/nukkit/entity/Entity.java
Reverts PowerNukkit/PowerNukkit#885
> Revert "Fix for missing effect particles after re-login"

- src/main/java/cn/nukkit/blockentity/BlockEntityBeacon.java
* Fix regen level
* Show effect particles
* Validate beacon update
* Fix high-level effect still applied after lowering power level
* Change spawn compound tags to match vanilla
> Fixes for beacon

- src/main/java/cn/nukkit/blockproperty/ArrayBlockProperty.java
- src/main/java/cn/nukkit/blockproperty/BlockProperties.java
- src/main/java/cn/nukkit/blockproperty/BlockProperty.java
- src/main/java/cn/nukkit/blockproperty/BooleanBlockProperty.java
- src/main/java/cn/nukkit/blockproperty/IntBlockProperty.java
- src/main/java/cn/nukkit/blockproperty/UnsignedIntBlockProperty.java
- src/main/java/cn/nukkit/blockproperty/exception/InvalidBlockPropertyPersistenceValueException.java
- src/main/java/cn/nukkit/blockstate/BlockState.java
- src/main/java/cn/nukkit/blockstate/BlockStateRegistry.java
Allows to get a `BlockState` from a runtime id
> Implements API to get the BlockState by runtime id

- CHANGELOG.md
- pom.xml
- src/main/java/cn/nukkit/Nukkit.java
- src/main/java/cn/nukkit/Server.java
- src/main/resources/log4j2.xml
Server owners can opt-out using `-DdisableSentry` or setting `disable-auto-bug-report` to true in `server.properties`
> Adds automatic bug reports using Sentry

- src/main/java/cn/nukkit/network/RakNetInterface.java
> Fix packet encoding issue

- src/main/java/cn/nukkit/Server.java
- src/main/java/cn/nukkit/entity/mob/EntityIronGolem.java
To test:
/give YourNick spawn_egg:20 1
> Adds Iron Golem

- src/main/java/cn/nukkit/network/RakNetInterface.java
Fix disconnect problems
(https://github.com/PowerNukkit/PowerNukkit/pull/925#issuecomment-770520525)
> Fix disconnect problems

- src/main/java/cn/nukkit/item/enchantment/trident/EnchantmentTridentImpaling.java
Implement Trident Enchantment Impaling
(I think I forgot to update this in #872)
> Implement Trident Enchantment Impaling

- CHANGELOG.md
- src/main/java/cn/nukkit/command/defaults/GiveCommand.java
- src/main/java/cn/nukkit/item/Item.java
- src/main/java/cn/nukkit/utils/BinaryStream.java
- src/main/resources/creativeitems.json
- src/main/resources/runtime_item_ids.json
> Fixes issues with Item.fromString the ordering of items in creative tabs

- CHANGELOG.md
- src/main/java/cn/nukkit/nbt/NBTIO.java
- src/test/java/cn/nukkit/nbt/NBTIOTest.java
> Fixes Unknown item mapping Item Unknown (879:3)

- src/main/java/cn/nukkit/item/Item.java
- src/main/java/cn/nukkit/utils/BinaryStream.java
Fix #1010
Also related to #857
> Fix Craftable items hints not working with tools

- src/main/java/cn/nukkit/blockstate/BlockState.java
- src/test/java/cn/nukkit/block/BlockWallTest.java
> Fix: Invalid items states in the inventory

- src/main/java/cn/nukkit/Server.java
- src/main/java/cn/nukkit/entity/Entity.java
- src/main/java/cn/nukkit/entity/item/EntityArmorStand.java
- src/main/java/cn/nukkit/item/ItemDye.java
- src/main/java/cn/nukkit/metrics/Metrics.java
- src/main/java/cn/nukkit/metrics/NukkitMetrics.java
- src/main/java/cn/nukkit/utils/NukkitCollectors.java
> Fixes many 1.4.0.0-PN issues

- src/main/java/cn/nukkit/Player.java
- src/main/java/cn/nukkit/api/API.java
- src/main/java/cn/nukkit/entity/Entity.java
- src/main/java/cn/nukkit/inventory/GrindstoneInventory.java
- src/main/java/cn/nukkit/network/protocol/types/NetworkInventoryAction.java
> #1061 Fix problem with grindstone, anvil and smithing table

- src/main/java/cn/nukkit/block/Block.java
- src/main/java/cn/nukkit/block/BlockBamboo.java
> Fixes wrong break time when breaking a bamboo with a sword

- Dockerfile
- pterodactyl-image-java11.Dockerfile
- pterodactyl-image-java8.Dockerfile
- release-script/release.py
- release-script/release_config.py
- release-script/release_config_local.py
Check the repository below in a few hours for details about the Pterodactyl images and eggs:
https://github.com/PowerNukkit/PowerNukkit-Pterodactyl-Egg
> Creates pterodactyl images to create an auto-updating egg

- src/main/java/cn/nukkit/block/BlockBed.java
> Fixes #29 Incorrect behaviour when trying to sleep on waterlogged bed

- src/main/java/cn/nukkit/Player.java
- src/main/java/cn/nukkit/block/BlockDoor.java
- src/main/java/cn/nukkit/block/BlockDoublePlant.java
- src/main/java/cn/nukkit/block/BlockTallGrass.java
- src/main/java/cn/nukkit/blockproperty/CommonBlockProperties.java
- src/main/java/cn/nukkit/blockproperty/value/DoublePlantType.java
- src/main/java/cn/nukkit/inventory/CraftingManager.java
- src/main/java/cn/nukkit/level/format/updater/DoorUpdater.java
Fixes #1075
Also fixes #1070, accidentally pushed to the same branch
> Fixes #1075 can't craft netherite axe and shovel. Fixes a cursor desync.

- src/main/java/cn/nukkit/blockentity/BlockEntityItemFrame.java
- src/main/java/cn/nukkit/item/Item.java
- src/main/java/cn/nukkit/item/RuntimeItems.java
- src/main/java/cn/nukkit/utils/BinaryStream.java
- src/main/resources/runtime_item_ids.json
> Fix Prismarine Crystals rendering incorrectly in item frames and ink_sac in recipes

- src/main/java/cn/nukkit/block/BlockCauldron.java
- src/main/java/cn/nukkit/blockentity/BlockEntityCauldron.java
- src/main/java/cn/nukkit/item/ItemDye.java
- src/main/java/cn/nukkit/utils/DyeColor.java
> Fix Incorrect dye names and block colors. Improves color mixing

- src/main/resources/runtime_item_ids.json
> Fix #1084 Custom spawn eggs not working

- src/main/java/cn/nukkit/Player.java
> Fixes #981 magma, lava, and starvation death messages

- src/main/java/cn/nukkit/Player.java
- src/main/java/cn/nukkit/PlayerFood.java
> Fixes #494 food level not decreasing correctly and client desyncs

- src/main/java/cn/nukkit/potion/Effect.java
> Fix Beacon speed wonky and health boost not being removed

- src/main/java/cn/nukkit/Player.java
- src/main/java/cn/nukkit/network/protocol/TickSyncPacket.java
> Implement TickSyncPacket

- src/main/java/cn/nukkit/network/Network.java
Register TickSyncPacket properly
I forgot to register it in #1115
> Register TickSyncPacket properly

- src/main/java/cn/nukkit/entity/Entity.java
The problem:
Place a boat
Enter the boat
/tp ~ ~10 ~
Now you have to reconnect to stop the glitch
> Dismount entities before teleporting

- src/main/java/cn/nukkit/block/Block.java
- src/main/java/cn/nukkit/block/BlockWood.java
- src/main/java/cn/nukkit/block/BlockWoodBark.java
- src/main/java/cn/nukkit/block/BlockWoodStripped.java
- src/main/java/cn/nukkit/blockstate/BlockStateRegistry.java
- src/main/java/cn/nukkit/blockstate/IBlockState.java
- src/main/java/cn/nukkit/blockstate/IMutableBlockState.java
- src/test/java/cn/nukkit/blockstate/IBlockStateTest.java
> Fix backward compatibility with plugins setting full bark logs with 17:13

- src/main/resources/runtime_item_ids.json
> soul_campfire and end_crystal rendering in inventory. Update translations.

- src/main/java/cn/nukkit/Player.java
- src/main/java/cn/nukkit/entity/Entity.java
- src/main/java/cn/nukkit/event/entity/EntityDamageEvent.java
- src/main/java/cn/nukkit/item/Item.java
- src/main/java/cn/nukkit/item/enchantment/Enchantment.java
- src/main/java/cn/nukkit/item/enchantment/EnchantmentFireAspect.java
- src/main/java/cn/nukkit/item/enchantment/sideeffect/SideEffect.java
- src/main/java/cn/nukkit/item/enchantment/sideeffect/SideEffectCombust.java
> Fix burning mobs and isOnFire() method

- src/main/java/cn/nukkit/block/Block.java
- src/main/java/cn/nukkit/block/BlockTuff.java
> Add Tuff Block

- src/main/java/cn/nukkit/Nukkit.java
- src/main/java/cn/nukkit/Player.java
- src/main/java/cn/nukkit/command/defaults/GameruleCommand.java
- src/main/java/cn/nukkit/item/ItemRedstone.java
- src/main/java/cn/nukkit/level/GameRule.java
- src/main/java/cn/nukkit/level/GameRules.java
- src/main/java/cn/nukkit/network/protocol/AddEntityPacket.java
- src/main/java/cn/nukkit/utils/BinaryStream.java
- src/main/resources/runtime_item_ids.json
CloudburstMC#1854)
(cherry picked from commit 818612eef6096d97df5daaf14882f0c63127a4e3)
> Register missing game rules & entity network IDs + bump API version

- src/main/java/cn/nukkit/block/Block.java
> Cobwebs are now breakable by using shears

- src/main/java/cn/nukkit/item/ItemFireCharge.java
Remove duplicated import of ItemFireCharge
> Remove duplicated import of ItemFireCharge

- src/main/java/cn/nukkit/level/Level.java
- src/main/java/cn/nukkit/utils/BinaryStream.java
- src/main/java/co/aikar/timings/Timings.java
- src/test/java/cn/nukkit/level/LevelTest.java
Updates translations and fixes issues reported by sonar
> Translation Updates and Sonar Fixes

- CHANGELOG.md
https://keepachangelog.com/en/1.0.0/
PowerNukkit devs, please update the changelog file here when changes are made to the software, this helps to keep people informed of what's going on in the project
> Let's keep a change log

- src/main/java/cn/nukkit/block/BlockRailPowered.java
When powering a powered rail it will not power up the others
> Fixes powered rails do not update in a row

- src/main/java/cn/nukkit/block/BlockFungusCrimson.java
- src/main/java/cn/nukkit/block/BlockFungusWarped.java
- src/main/java/cn/nukkit/level/generator/object/tree/ObjectCrimsonTree.java
- src/main/java/cn/nukkit/level/generator/object/tree/ObjectNetherTree.java
- src/main/java/cn/nukkit/level/generator/object/tree/ObjectWarpedTree.java
I'm very sorry for the spam of PRs, this should be final though, if not someone can go ahead and readd it!
Edit: Works now with only the commit for adding tree generation!
> Added Nether Fungi Generation via Bonemeal

- src/main/java/cn/nukkit/utils/BinaryStream.java
- src/test/java/cn/nukkit/utils/BinaryStreamTest.java
Players who have bad items in the inventory will not be locked outside the server anymore.
> Improves unknown item handling, shows unknown block instead of disconnections

- src/main/java/cn/nukkit/block/Block.java
- src/main/java/cn/nukkit/block/BlockBricksDeepslate.java
- src/main/java/cn/nukkit/block/BlockBricksDeepslateCracked.java
- src/main/java/cn/nukkit/block/BlockDeepslateChiseled.java
- src/main/java/cn/nukkit/block/BlockDoubleSlabBrickDeepslate.java
- src/main/java/cn/nukkit/block/BlockDoubleSlabDeepslatePolished.java
- src/main/java/cn/nukkit/block/BlockDoubleSlabTileDeepslate.java
- src/main/java/cn/nukkit/block/BlockInfestedDeepslate.java
- src/main/java/cn/nukkit/block/BlockMonsterEgg.java
- src/main/java/cn/nukkit/block/BlockSlabBrickDeepslate.java
- src/main/java/cn/nukkit/block/BlockSlabDeepslatePolished.java
- src/main/java/cn/nukkit/block/BlockSlabTileDeepslate.java
- src/main/java/cn/nukkit/block/BlockStairsBrickDeepslate.java
- src/main/java/cn/nukkit/block/BlockStairsDeepslateCobbled.java
- src/main/java/cn/nukkit/block/BlockStairsDeepslatePolished.java
- src/main/java/cn/nukkit/block/BlockStairsTileDeepslate.java
- src/main/java/cn/nukkit/block/BlockTilesDeepslate.java
- src/main/java/cn/nukkit/block/BlockTilesDeepslateCracked.java
- src/main/java/cn/nukkit/block/BlockWallBrickDeepslate.java
- src/main/java/cn/nukkit/block/BlockWallDeepslateCobbled.java
- src/main/java/cn/nukkit/block/BlockWallDeepslatePolished.java
- src/main/java/cn/nukkit/block/BlockWallTileDeepslate.java
Add all deepslate related blocks and some fixes
> Add all deepslate related blocks and some fixes

- src/main/java/cn/nukkit/entity/EntityCreature.java
- src/main/java/cn/nukkit/entity/EntityNameable.java
This pull request fixes #1298.
> Fix nametag being applied on adventure mode (#1298)
